name: 'Semantic Release Action'
description: 'Automate the whole package release workflow with semantic-release.'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: false
  repo_name:
    description: 'The name of the repository'
    required: false
  version_bump_mode:
    description: 'The version bump to use'
    required: false
    default: 'prlabel'
  prerelease:
    description: 'Create a pre-release'
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
