name: 'Advanced Semantic Release Action'
description: 'Automate the whole package release workflow with semantic-release.'

branding:
  icon: 'package'
  color: 'red'

inputs:
  github_token:
    description: 'The GitHub token to use for authentication'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: false
  repo_name:
    description: 'The name of the repository'
    required: false
  version_bump:
    description: 'The version bump to use. Not applicable if release_mode is promote.'
    required: false
  release_mode:
    description: 'Type of release to perform. Can be one of: release, prerelease, promote.'
    required: false
    default: 'prerelease'
  promote_from:
    description: 'The prerelease version to promote from. Not applicable if release_mode is not promote.'
    required: false

outputs:
  release_created:
    description: 'Whether a release was created'
  tag_name:
    description: 'The version that was released'
  prerelease:
    description: 'Whether the release is a prerelease'
  body:
    description: 'The body of the release'
  publish_version:
    description: 'The build version of the release'
  release_type:
    description: 'The type of release. Either beta or release.'

runs:
  using: 'node16'
  main: 'dist/index.js'
